.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TD2PLANET 1 "2007-2-23"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
td2planet \- planet implementation of ruby.
.SH SYNOPSIS
.B td2planet
.RI [ options ] " config.yaml"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B td2planet
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBtd2planet\fP is a planet program that read rss feed from your 
configuration then write html file.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-n, \-\-dry-run
do not fetch, generate files only.
.SH SEE ALSO
.BR ruby (1).
.SH AUTHOR
td2planet was written by Kazuhiro NISHIYAMA <zn@mbf.nifty.com>.
.PP
This manual page was written by Yukiharu YABUKI <yabuki@netfort.gr.jp>,
for the Debian project (but may be used by others).
